---
- hosts: localhost
  gather_facts: False
  

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: "{{key_name}}"
         instance_type: t2.micro
         image: ami-0b898040803850657
         wait: yes
         group: webserver
         count: 1
         vpc_subnet_id: "{{subnet}}"
         assign_public_ip: yes
