---
- hosts: localhost
  gather_facts: False
  

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: work
         region: us-east-1
         group: test
         instance_type: t2.micro
         state: running
         image:  ami-0b898040803850657
         wait: true
         exact_count: 5
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2
