---
- hosts: localhost
  gather_facts: False
  

  tasks:

    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        validate_certs: no
        datacenter: VCloud-East
        cluster: vCloud
        name: tower-test-01
        state: poweredon
        guest_id: centos64Guest
        resource_pool: Div_184
        folder: /VCloud-East/Sandbox
        disk:
        - size_gb: 50
          type: thin
          datastore: G-TINTRI-04
        hardware:
          memory_mb: 512
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VLAN_175
          vlan: 175
        wait_for_ip_address: no
      delegate_to: localhost
      register: deploy_vm





